### ISSUE TITLE
How create MetaClasses 

### ISSUE THREAD

**Issue by Javingka** [protegeproject/protege-distribution#20]
Hi everyone,

Sorry use this channel for asking, but I couldn't find a better place.
My question I hope is simple. 

**How can I create a Metaclass?**

I found [this link](https://protegewiki.stanford.edu/wiki/PrF_UG_meta_metaclass_create) but makes reference to a version of Protege called 'protege-frames' that I couldn't find how to download or install.

Thanks so much in advance.

My actual version is 5.5.0

**Comment by matthewhorridge** [comment]
I've answered your post on the Protege mailing list
