### ISSUE TITLE
Add Pellet 2.4

### ISSUE THREAD

**Issue by JulioJu** [protegeproject/protege-distribution#21]
Hi !

Pellet seams to be a very famous reasoner. Why don't add it in this release of Protege ? 

The main advantage of Pellet is its support of custom Datatypes. HermiT does not support custom Datatypes.

Version 2.4 could be build from sources at https://github.com/stardog-union/pellet with oracle-jdk11 or openjdk11 (but not jdk12 as "javac -source and -target Options, support for the 6/1.6 argument value for javac's -source, -target, and --release flags has been removed." https://www.oracle.com/technetwork/java/javase/12-relnote-issues-5211422.html )

Thanks in advance !

**Comment by matthewhorridge** [comment]
Pellet is available via auto-update in Protege.  The distribution of Pellet is controlled by Stardog Union. 

By the way, there's no version 2.4 release (it's just a snapshot build - and it's not clear if there are actually any real changes between 2.4-snapshot or whether it was just a bump in version number).

**Comment by Zack-83** [comment]
Sorry to contradict you, but Pellet is not included in the present release. I had to download it by hand from https://github.com/stardog-union/pellet/tree/master/protege/plugin.
