### ISSUE TITLE
Use consistent GitHub release tag names

### ISSUE THREAD

**Issue by TheSentry** [protegeproject/protege-distribution#48]
I realized that the naming scheme for release tags is very inconsistent.

See https://github.com/protegeproject/protege-distribution/tags

For example, the following tags are used:
- protege-5.0.0
- v5.1.0
- v5.2.0
- v5.5.0-beta-2
- 5.5.0-beta-3
- v5.5.0
- protege-5.6.0

If you're writing a script to automatically check for the current version, the changing naming schemes really make it harder than it has to be.

Plus, I'm a bit compulsive on that ;)

**Comment by gouttegd** [comment]
Starting from version 5.6.0 the same scheme is always used:

* for the Protégé distribution (this repository): `protege-X.Y.Z`
* for the core software (https://github.com/protegeproject/protege): `protege-parent-X.Y.Z`

I intend to stick to that scheme for the future releases.

**Comment by TheSentry** [comment]
That certainly would be nice.

Thank you for the quick response!
